name: Deploy to Production

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        environment:
            name: production
            url: https://pricey.yourdomain.com

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.PRODUCTION_HOST }}
                  username: ${{ secrets.PRODUCTION_USER }}
                  key: ${{ secrets.PRODUCTION_SSH_KEY }}
                  port: ${{ secrets.PRODUCTION_PORT || 22 }}
                  script: |
                      cd /app/pricey
                      git pull origin main
                      docker-compose pull
                      docker-compose up -d --build
                      docker-compose exec -T app npm run prisma:migrate
                      docker system prune -af

            - name: Deployment notification
              if: always()
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  text: "Deployment to production ${{ job.status }}"
                  webhook_url: ${{ secrets.SLACK_WEBHOOK }}
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
